@server = http://localhost:8000/api/auth

# invalid username and password
POST {{server}}
Content-Type: application/json

{
    "username": "dsajgkhjks",
    "password": "faasdkfhdsauhf"
}

# invalid password
###
POST {{server}}
Content-Type: application/json

{
    "username": "john",
    "password": "faasdkfhdsauhf"
}