@server =  http://localhost:8000/api/users


# All users
GET {{server}}

###
# Get user by id
GET {{server}}/user-by-id/1

###
# Create user
POST {{server}}/create
Content-Type: application/json

{
    "username": "john",
    "password": "testpassword",
    "email": "test123@gmail.com"
}
